version: '3.8'

services:
  market-maker-bot:
    build: .
    container_name: polymarket-market-maker-bot
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    ports:
      - "9305:9305"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

